# Programming for Data Analysis 2019
Submitted by Paula Daly

This Juypter notebook has been created to review the numpy.random package in Python.  This notebook will cover:

1. The overall purpose of the numpy.random package.
2. The use of the “Simple random data” and “Permutations” functions within the numpy.random package.
3. The use and purpose of the follwoing five “Distributions” functions.
4. Explaination of the use of seeds in generating pseudorandom numbers.

# The purpose of the numpy.random package
NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed.

Using NumPy, a developer can perform the following operations −

 - Mathematical and logical operations on arrays.

 - Fourier transforms and routines for shape manipulation.

 - Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation

For this project I am investigating the numpy.random module within the numpy library.  The random module in Numpy package contains many functions for generation of random numbers.  It has teh ability to generate random lists of data, shuffle exiting data and draw samples based on specific distributions.

# Functions: Simple random data and Permutations

# Simple random data
Return a sample (or samples) from the “standard normal” distribution. Return random integers from low (inclusive) to high (exclusive). Random integers of type np.int between low and high, inclusive. Return random floats in the half-open interval [0.0, 1.0).

I have ran some funtions to show how simple lists of data are generated using numpy.random.  Everytime you run below functions you will get a different set of random numbers

In [47]:
# Import Numpy
import numpy as np

In [28]:
# Random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

[[0.38573763 0.26665388]
 [0.83351068 0.28259663]]


In [29]:
# Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(2,2))

[[-0.02144316  0.73322504]
 [-0.50296785 -2.27763809]]


In [30]:
# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))

[[8 0]
 [5 3]]


In [31]:
# One random number between [0,1)
print(np.random.random())

0.3829942233680509


In [32]:
# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))

[[0.45578193 0.32851571]
 [0.86043424 0.92175681]]


In [33]:
# Pick 10 items from a given list, with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))  

['u' 'i' 'u' 'u' 'e' 'u' 'a' 'i' 'a' 'i']


In [34]:
# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1])) 

['o' 'a' 'o' 'a' 'o' 'o' 'u' 'e' 'o' 'a']


# Permutations¶
no of pos
shuffle(x)	Modify a sequence in-place by shuffling its contents.
permutation(x)	Randomly permute a sequence, or return a permuted range.

# Distributions


In [ ]:
Normal Distribution:
    
The most widely distribution encountered is the normal distribution also known as the Bell Curve.  
A normal distribution is described by just two numbers, the mean and Standard Deviation.  
The mean is the average, it’s where the Bell Curve peaks.  
The Standard Deviation describes how wide or narrow the curve is.   
You use the Greek letter μ (mu) for the mean or expectation of the distribution (and also its median and mode)
The Greek letter σ (sigma) is used for the standard deviation. 



To generate random numbers from a normal distribution you use the normalvariate function - normalvariate(μ, σ) you must pass in both the mean and the standard deviation.
For example to generate 20 numbers from a bell curve with a mean of 0 and a standard deviation of 1 you call the normalvariate function and pass in the two parameters.
Import random
For i in range(20):
  Print(random.normalvariate(0, 1))

Notice how the numbers are bunched around the mean zero.

Here is an example generating 20 numbers of a bell curve with a mean of 0 and a standard deviation of 9.
Import random
For i in range(20):
  Print(random.normalvariate(0, 9))

Notice that these numbers are more widely spread out.


If you make the standard deviation small the random numbers will be more tightly grouped.
Import random
For i in range(20):
  Print(random.normalvariate(0, 0.2))


In [27]:
i = np.random.rand(20)
print(random.normalvariate(0, 1))

-1.2355856731126345


In [46]:
for i in range(20)
  print (random.normalvariate(0,9))

SyntaxError: invalid syntax (<ipython-input-46-a6dcf76bfd46>, line 1)

# Seed The Random Number Generator
The pseudorandom number generator is a mathematical function that generates a sequence of nearly random numbers.

It takes a parameter to start off the sequence, called the seed. The function is deterministic, meaning given the same seed, it will produce the same sequence of numbers every time. The choice of seed does not matter.

The seed() function will seed the pseudorandom number generator, taking an integer value as an argument, such as 1 or 7. If the seed() function is not called prior to using randomness, the default is to use the current system time in milliseconds from epoch (1970).

The example below demonstrates seeding the pseudorandom number generator, generates some random numbers, and shows that reseeding the generator will result in the same sequence of numbers being generated.

If you want to repeat the same set of random numbers every time you need to set the seed or random state.  The seed can be any value, the only requirement is that you must set the seed to the same value every time you want to generate the same set of random numbers.

Once np.random.RandomState is created all the function of the np.random module become available to the created randomstate object.

In [40]:
# Create the random state
rn = np.random.RandomState(100)

In [41]:
# Create random numbers between [0,1) of shape 2,2
print(rn.rand(2,2))

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]


In [42]:
# Set the random seed
np.random.seed(100)

In [43]:
# Create randim numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]
